[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:streamlit]
command=streamlit run /app/app.py
    --server.port=8501
    --server.address=127.0.0.1
    --server.headless=true
    --server.enableCORS=false
    --server.enableXsrfProtection=false
    --browser.serverAddress=pokemon-alb-2097119654.us-east-1.elb.amazonaws.com
    --browser.serverPort=80
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
