[server]
port = 8080
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = false
headless = true
enableWebsocketCompression = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[runner]
fastReruns = false
